In [1]:
import shap
X,y = shap.datasets.nhanesi()
X_display,y_display = shap.datasets.nhanesi(display=True)

In [2]:
X

,Unnamed: 0,Age,Diastolic BP,Poverty index,Race,Red blood cells,Sedimentation rate,Serum Albumin,Serum Cholesterol,Serum Iron,Serum Magnesium,Serum Protein,Sex,Systolic BP,TIBC,TS,White blood cells,BMI,Pulse pressure
0,0,35.0,92.0,126.0,2.0,77.7,12.0,5.0,165.0,135.0,1.37,7.6,2.0,142.0,323.0,41.8,5.8,31.109434,50.0
1,1,71.0,78.0,210.0,2.0,77.7,37.0,4.0,298.0,89.0,1.38,6.4,2.0,156.0,331.0,26.9,5.3,32.362572,78.0
2,2,74.0,86.0,999.0,2.0,77.7,31.0,3.8,222.0,115.0,1.37,7.4,2.0,170.0,299.0,38.5,8.1,25.388497,84.0
3,3,64.0,92.0,385.0,1.0,77.7,30.0,4.3,265.0,94.0,1.97,7.3,2.0,172.0,349.0,26.9,6.7,26.446610,80.0
4,4,32.0,70.0,183.0,2.0,77.7,18.0,5.0,203.0,192.0,1.35,7.3,1.0,128.0,386.0,49.7,8.1,20.354684,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9927,9927,26.0,76.0,491.0,1.0,46.6,9.0,4.7,137.0,90.0,1.39,7.4,1.0,104.0,316.0,28.5,10.7,21.468805,28.0
9928,9928,69.0,82.0,316.0,1.0,48.0,18.0,4.7,301.0,98.0,2.02,6.7,2.0,130.0,334.0,29.3,7.1,23.090226,48.0
9929,9929,34.0,80.0,187.0,1.0,47.3,10.0,4.5,161.0,95.0,1.54,6.9,2.0,110.0,381.0,24.9,5.4,25.797680,30.0
9930,9930,57.0,84.0,999.0,1.0,54.7,5.0,4.5,210.0,93.0,1.82,7.0,1.0,130.0,337.0,27.6,6.2,23.406200,46.0
9931,9931,70.0,70.0,204.0,1.0,48.8,9.0,4.4,205.0,124.0,1.91,6.8,1.0,132.0,398.0,31.2,7.5,28.763104,62.0

In [3]:
y

array([ 15.27465753,  11.58607306,   8.14908676, ..., -18.87716895,
       -19.68310502,  17.93858447])

In [4]:
X_display

,Unnamed: 0,Age,Diastolic BP,Poverty index,Race,Red blood cells,Sedimentation rate,Serum Albumin,Serum Cholesterol,Serum Iron,Serum Magnesium,Serum Protein,Sex,Systolic BP,TIBC,TS,White blood cells,BMI,Pulse pressure
0,0,35.0,92.0,126.0,2.0,77.7,12.0,5.0,165.0,135.0,1.37,7.6,Female,142.0,323.0,41.8,5.8,31.109434,50.0
1,1,71.0,78.0,210.0,2.0,77.7,37.0,4.0,298.0,89.0,1.38,6.4,Female,156.0,331.0,26.9,5.3,32.362572,78.0
2,2,74.0,86.0,999.0,2.0,77.7,31.0,3.8,222.0,115.0,1.37,7.4,Female,170.0,299.0,38.5,8.1,25.388497,84.0
3,3,64.0,92.0,385.0,1.0,77.7,30.0,4.3,265.0,94.0,1.97,7.3,Female,172.0,349.0,26.9,6.7,26.446610,80.0
4,4,32.0,70.0,183.0,2.0,77.7,18.0,5.0,203.0,192.0,1.35,7.3,Male,128.0,386.0,49.7,8.1,20.354684,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9927,9927,26.0,76.0,491.0,1.0,46.6,9.0,4.7,137.0,90.0,1.39,7.4,Male,104.0,316.0,28.5,10.7,21.468805,28.0
9928,9928,69.0,82.0,316.0,1.0,48.0,18.0,4.7,301.0,98.0,2.02,6.7,Female,130.0,334.0,29.3,7.1,23.090226,48.0
9929,9929,34.0,80.0,187.0,1.0,47.3,10.0,4.5,161.0,95.0,1.54,6.9,Female,110.0,381.0,24.9,5.4,25.797680,30.0
9930,9930,57.0,84.0,999.0,1.0,54.7,5.0,4.5,210.0,93.0,1.82,7.0,Male,130.0,337.0,27.6,6.2,23.406200,46.0
9931,9931,70.0,70.0,204.0,1.0,48.8,9.0,4.4,205.0,124.0,1.91,6.8,Male,132.0,398.0,31.2,7.5,28.763104,62.0

In [5]:
y_display

array([ 15.27465753,  11.58607306,   8.14908676, ..., -18.87716895,
       -19.68310502,  17.93858447])

In [6]:
from sksurv.datasets import load_aids

ModuleNotFoundError: No module named 'sksurv'